---
# globals section
network_globals:
  network_ula_prefix: ""
  network_packet_steering: ""

# device section
network_devices: []

# bridge vlans
bridge_vlans: []

# interface section
network_interfaces: []

# rule section
network_rules: []

# route section
network_routes: []
