---
# dnsmasq section
dhcp_dnsmasq_section_id: "main"

dhcp_common:
  authoritative: ""
  boguspriv: ""
  cachesize: ""
  domain: ""
  domainneeded: ""
  dnssec: ""
  dnsseccheckunsigned: ""
  expandhosts: ""
  filterwin2k: ""
  fqdn: ""
  leasefile: ""
  local: ""
  localise_queries: ""
  localservice: ""
  nonegcache: ""
  nonwildcard: ""
  readethers: ""
  rebind_protection: ""
  rebind_localhost: ""
  rebind_domain: []
  resolvfile: ""
  server: []
  serverlist: ""
  address: []
  allservers: ""

# dhcp section
dhcp_pools: []

# host section
dhcp_leases: []
