---
version: "3"

tasks:
  test:
    dir: test
    cmds:
      - echo "Run test playbook for opewnrt devices"
      - ansible-galaxy collection install -r requirements.yml -p ../.collections
      - ansible-playbook --inventory inventory.yml playbook.yml
