---
galaxy_info:
  author: flyoverhead
  description: Configure wireless settings
  license: GPL-3.0
  min_ansible_version: "2.18"
  platforms:
    - name: OpenWrt
      versions: ["22.03", "23.05", "24.10"]
  galaxy_tags: ["openwrt", "wireless"]
dependencies:
  - role: community.openwrt.init
