---
- name: Preflight and name system sections
  ansible.builtin.include_role:
    name: uci_migration
  vars:
    uci_migration_selected_packages: ["system"]
  when: "'system' not in (uci_migration_prepared_packages | default([]))"

# Configure system section
- name: Configure system section
  ansible.builtin.include_tasks: system.yml

# Apply changes and reload system service
- name: Apply changes and reload system
  block:
    # Commit changes
    - name: Commit changes
      community.openwrt.uci:
        command: commit
        config: "system"
      notify: Reload system

    # Reload system service
    - name: Reload system service
      ansible.builtin.meta: flush_handlers
