---
# Configure globals settings
- name: Configure globals settings
  community.openwrt.uci:
    command: "section"
    config: "network"
    name: "globals"
    find: {}
    type: "globals"
    value:
      ula_prefix: "{{ network_globals.network_ula_prefix | default(omit) }}"
      packet_steering: "{{ network_globals.network_packet_steering | default(omit) }}"
