---
# Wireguard packages
wireguard_pkgs:
  ["wireguard-tools", "luci-proto-wireguard", "luci-app-wireguard", "qrencode"]

# Wireguard servers
wireguard_interfaces: []

# Wireguard peers
wireguard_peers: []
