---
# Set extroot status to false
# to prevent permanent configuration
- name: Set default extroot status fact to false
  ansible.builtin.set_fact:
    extroot_configure: false

# Check current extroot status
- name: Check current extroot status
  community.openwrt.uci:
    command: "find"
    config: "fstab"
    type: "mount"
    option: "target"
    find: "/overlay"
  register: extroot_status
  failed_when: false
  changed_when: false

# Set extroot status fact
- name: Set extroot status fact
  ansible.builtin.set_fact:
    extroot_configure: true
  when: extroot_status.result | default('') | length == 0
